services:
  api:
    command: ["npm", "run", "test"]
    build: "images/api"
    image: quentinmgn/api
    container_name: api
    ports:
      - 3000:3000
    environment:
      NODE_ENV:
      POSTGRES_HOST:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test", "-d", "test"]
      interval: 5s
      timeout: 4s
      retries: 10
      start_period: 10s
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST_AUTH_METHOD:
    volumes:
      - ./_volumes/database:/var/lib/postgresql/data
